"""update_payment_schema

Revision ID: 2cc9fca805a7
Revises: d561e880f8d7
Create Date: 2026-06-13 00:30:58.997579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc9fca805a7'
down_revision: Union[str, Sequence[str], None] = 'd561e880f8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.create_check_constraint('check_amount', 'payments', 'amount > 0')
    op.create_check_constraint('check_currency_format', 'payments', "currency ~ '^[A-Z]{3}$'")
    op.add_column('payments', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('customer_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_currency_format', 'payments', type_='check')
    op.drop_constraint('check_amount', 'payments', type_='check')
    op.alter_column('payments', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.alter_column('payments', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'completed_at')
    op.drop_column('payments', 'customer_id')
    op.drop_column('payments', 'external_id')
    # ### end Alembic commands ###
