"""Update outbox schema

Revision ID: 6da30aa906f2
Revises: 2cc9fca805a7
Create Date: 2026-07-02 21:32:08.653765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da30aa906f2'
down_revision: Union[str, Sequence[str], None] = '2cc9fca805a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    outbox_status = sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='outboxstatus')
    outbox_status.create(op.get_bind())
    op.add_column('outbox_events', sa.Column('status', outbox_status, nullable=False, server_default='PENDING'))
    op.add_column('outbox_events', sa.Column('reserved_to', sa.DateTime(), nullable=True))
    op.drop_column('outbox_events', 'published')
    op.drop_constraint(op.f('payments_idempotency_key_key'), 'payments', type_='unique')
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.create_unique_constraint(op.f('payments_idempotency_key_key'), 'payments', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.add_column('outbox_events', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('outbox_events', 'reserved_to')
    op.drop_column('outbox_events', 'status')
    outbox_status = sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='outboxstatus')
    outbox_status.drop(op.get_bind())
    # ### end Alembic commands ###
