"""init saga schema

Revision ID: 48bf76f32db7
Revises: 
Create Date: 2026-07-13 23:50:57.011508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48bf76f32db7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('saga_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_processed_events_saga_id'), 'processed_events', ['saga_id'], unique=False)
    op.create_table('sagas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'INVENTORY_RESERVING', 'INVENTORY_RESERVED', 'PAYMENT_CHARGING', 'COMPENSATING_INVENTORY', 'COMPLETED', 'CANCELLED', 'FAILED', name='sagastatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_after', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sagas_order_id'), 'sagas', ['order_id'], unique=True)
    op.create_index(op.f('ix_sagas_retry_after'), 'sagas', ['retry_after'], unique=False)
    op.create_index(op.f('ix_sagas_status'), 'sagas', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sagas_status'), table_name='sagas')
    op.drop_index(op.f('ix_sagas_retry_after'), table_name='sagas')
    op.drop_index(op.f('ix_sagas_order_id'), table_name='sagas')
    op.drop_table('sagas')
    op.drop_index(op.f('ix_processed_events_saga_id'), table_name='processed_events')
    op.drop_table('processed_events')
    # ### end Alembic commands ###
